# The message to control the panel buttons of the CAT793F

std_msgs/Header header           # CAT793F panel buttons state at this time

bool autoretarder_down                     
bool autoretarder_up
bool retardercontrol_on
bool retardercontrol_off     		       
bool throttlelock           
bool window_up
bool window_down               
          
bool hazerdlight   
bool headlight_mid      
bool headlight_up 
bool foglight 
bool stairwaylight
bool heatedmirror
bool panellight_up
bool panellight_down
bool transmission_yellow_down
bool transmission_yellow_up

bool leftturnsignal
bool rightturnsignal
bool wiperlow  			
bool wiperhigh
bool windshieldwasherfluid
bool highbean
bool horn
bool enginekeyon        
bool enginekeycrank
bool seatbelt

bool firesupression

